Tank:
  turret_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - TURRET_Y
      - TURRET_P
    gains:
      TURRET_Y:
        p: 100
        i: 10
        d: 1
      TURRET_P:
        p: 100
        i: 10
        d: 1
